#!/usr/bin/expect -f

set timeout 60

puts "========================================="
puts "為 IP 地址創建自簽名 SSL 憑證"
puts "=========================================\n"
puts "⚠️  注意: 自簽名憑證會被瀏覽器標記為「不安全」"
puts "   建議用於開發/測試環境\n"

spawn ssh root@172.238.14.142
expect "password:"
send "@Joendle396\r"
expect "root@*"

send "cd /opt/directconverter\r"
expect "root@*"

# 創建 SSL 目錄
send "mkdir -p /etc/nginx/ssl\r"
expect "root@*"

# 生成自簽名憑證
send "openssl req -x509 -nodes -days 365 -newkey rsa:2048 \\\r"
expect ">"
send "-keyout /etc/nginx/ssl/selfsigned.key \\\r"
expect ">"
send "-out /etc/nginx/ssl/selfsigned.crt \\\r"
expect ">"
send "-subj '/C=TW/ST=Taiwan/L=Taipei/O=DirectConverter/CN=172.238.14.142'\r"
expect "root@*"

# 備份原配置
send "cp /etc/nginx/sites-available/directconverter /etc/nginx/sites-available/directconverter.bak\r"
expect "root@*"

# 更新 Nginx 配置添加 HTTPS
send "cat > /etc/nginx/sites-available/directconverter << 'EOF'\r"
expect ">"
send "# HTTP -> HTTPS 重定向\r"
expect ">"
send "server {\r"
expect ">"
send "    listen 80;\r"
expect ">"
send "    server_name 172.238.14.142;\r"
expect ">"
send "    return 301 https://\$server_name\$request_uri;\r"
expect ">"
send "}\r"
expect ">"
send "\r"
expect ">"
send "# HTTPS 配置\r"
expect ">"
send "server {\r"
expect ">"
send "    listen 443 ssl http2;\r"
expect ">"
send "    server_name 172.238.14.142;\r"
expect ">"
send "\r"
expect ">"
send "    ssl_certificate /etc/nginx/ssl/selfsigned.crt;\r"
expect ">"
send "    ssl_certificate_key /etc/nginx/ssl/selfsigned.key;\r"
expect ">"
send "    ssl_protocols TLSv1.2 TLSv1.3;\r"
expect ">"
send "    ssl_ciphers HIGH:!aNULL:!MD5;\r"
expect ">"
send "\r"
expect ">"
send "    client_max_body_size 50M;\r"
expect ">"
send "\r"
expect ">"
send "    # Frontend\r"
expect ">"
send "    location / {\r"
expect ">"
send "        proxy_pass http://localhost:3000;\r"
expect ">"
send "        proxy_http_version 1.1;\r"
expect ">"
send "        proxy_set_header Upgrade \$http_upgrade;\r"
expect ">"
send "        proxy_set_header Connection 'upgrade';\r"
expect ">"
send "        proxy_set_header Host \$host;\r"
expect ">"
send "        proxy_cache_bypass \$http_upgrade;\r"
expect ">"
send "        proxy_set_header X-Real-IP \$remote_addr;\r"
expect ">"
send "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;\r"
expect ">"
send "        proxy_set_header X-Forwarded-Proto \$scheme;\r"
expect ">"
send "    }\r"
expect ">"
send "\r"
expect ">"
send "    # Backend API\r"
expect ">"
send "    location /api/ {\r"
expect ">"
send "        proxy_pass http://localhost:8000/api/;\r"
expect ">"
send "        proxy_http_version 1.1;\r"
expect ">"
send "        proxy_set_header Upgrade \$http_upgrade;\r"
expect ">"
send "        proxy_set_header Connection 'upgrade';\r"
expect ">"
send "        proxy_set_header Host \$host;\r"
expect ">"
send "        proxy_cache_bypass \$http_upgrade;\r"
expect ">"
send "        proxy_set_header X-Real-IP \$remote_addr;\r"
expect ">"
send "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;\r"
expect ">"
send "        proxy_set_header X-Forwarded-Proto \$scheme;\r"
expect ">"
send "    }\r"
expect ">"
send "\r"
expect ">"
send "    # Backend 文件下載\r"
expect ">"
send "    location /download/ {\r"
expect ">"
send "        proxy_pass http://localhost:8000/download/;\r"
expect ">"
send "        proxy_http_version 1.1;\r"
expect ">"
send "        proxy_set_header Host \$host;\r"
expect ">"
send "        proxy_set_header X-Real-IP \$remote_addr;\r"
expect ">"
send "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;\r"
expect ">"
send "    }\r"
expect ">"
send "}\r"
expect ">"
send "EOF\r"
expect "root@*"

send "nginx -t\r"
expect "root@*"
send "systemctl reload nginx\r"
expect "root@*"

send "echo '\n=== 測試 HTTPS ==='\r"
expect "root@*"
send "curl -I -k https://172.238.14.142 2>&1 | head -5\r"
expect "root@*"

send "exit\r"
expect eof

puts "\n========================================="
puts "✅ 自簽名 SSL 憑證已設置!"
puts "=========================================\n"
puts "🌐 訪問網址:"
puts "  • HTTPS: https://172.238.14.142"
puts "  • HTTP 會自動重定向到 HTTPS\n"
puts "⚠️  瀏覽器警告:"
puts "  首次訪問時,瀏覽器會顯示「您的連線不安全」"
puts "  這是正常的,因為使用自簽名憑證"
puts "  點擊「進階」->「繼續前往」即可\n"
puts "💡 建議:"
puts "  生產環境請使用真實域名和 Let's Encrypt 憑證"
puts "  執行: ./setup-ssl.sh your-domain.com\n"
puts "=========================================\n"
