#!/usr/bin/expect -f

set timeout 30

puts "\n========================================="
puts "🎉 DirectConverter 部署成功!"
puts "=========================================\n"

spawn ssh root@172.238.14.142
expect "password:"
send "@Joendle396\r"
expect "root@*"

send "cd /opt/directconverter\r"
expect "root@*"

send "echo '=== 容器狀態 ==='\r"
expect "root@*"
send "docker-compose ps\r"
expect "root@*"

send "echo '\n=== 測試主頁 ==='\r"
expect "root@*"
send "curl -I http://172.238.14.142 2>&1 | head -8\r"
expect "root@*"

send "echo '\n=== 測試 API ==='\r"
expect "root@*"
send "curl http://172.238.14.142/api/formats 2>&1 | python3 -m json.tool 2>/dev/null | head -20 || curl http://172.238.14.142/api/formats 2>&1 | head -10\r"
expect "root@*"

send "echo '\n=== 磁碟使用 ==='\r"
expect "root@*"
send "df -h | grep -E '(Filesystem|/$)'\r"
expect "root@*"

send "echo '\n=== 記憶體使用 ==='\r"
expect "root@*"
send "free -h\r"
expect "root@*"

send "exit\r"
expect eof

puts "\n========================================="
puts "✅ 部署驗證完成!"
puts "=========================================\n"
puts "📋 部署資訊:"
puts "  • 主機: Linode Ubuntu 24.04.3 LTS"
puts "  • IP: 172.238.14.142"
puts "  • 訪問網址: http://172.238.14.142"
puts "  • API 文檔: http://172.238.14.142/api/docs"
puts ""
puts "🐳 容器資訊:"
puts "  • 後端: FastAPI + Uvicorn (Port 8000)"
puts "  • 前端: Vite + React (Port 3000)"
puts "  • 反向代理: Nginx (Port 80)"
puts ""
puts "📝 管理指令:"
puts "  查看日誌:"
puts "    ssh root@172.238.14.142 'cd /opt/directconverter && docker-compose logs -f'"
puts ""
puts "  重啟服務:"
puts "    ssh root@172.238.14.142 'cd /opt/directconverter && docker-compose restart'"
puts ""
puts "  停止服務:"
puts "    ssh root@172.238.14.142 'cd /opt/directconverter && docker-compose down'"
puts ""
puts "  啟動服務:"
puts "    ssh root@172.238.14.142 'cd /opt/directconverter && docker-compose up -d'"
puts ""
puts "  檢查狀態:"
puts "    ssh root@172.238.14.142 'cd /opt/directconverter && docker-compose ps'"
puts ""
puts "🔄 更新代碼:"
puts "  1. 本地修改代碼"
puts "  2. 上傳: rsync -avz --exclude node_modules --exclude __pycache__ ./ root@172.238.14.142:/opt/directconverter/"
puts "  3. 重建: ssh root@172.238.14.142 'cd /opt/directconverter && docker-compose up -d --build'"
puts ""
puts "🔒 安全提示:"
puts "  • 建議修改 root 密碼"
puts "  • 建議設置 SSH 密鑰登入"
puts "  • 建議配置防火牆規則"
puts "  • 可以考慮添加域名和 SSL 憑證"
puts "=========================================\n"
